### ISSUE TITLE
Unable to change directories when exposed via Mina SFTP

### ISSUE THREAD

**Issue by ptirador** [carlspring/s3fs-nio#146]
# Task Description
When using S3FS as a file system for Mina SFTP, it's not possible to change the directory (`cd` command):

```
sftp> ls -l
d---------   1 OWNER@   GROUP@          0 Jan 25 10:51 bar
d---------   1 OWNER@   GROUP@          0 Jan 25 10:42 foo
sftp> cd foo
Can't change directory: Can't check target
```

POSIX permissions are not being returned for these directories, which is causing an exception in the SFTP client when attempting to `cd` to the directory. 

# Tasks

The following tasks will need to be carried out:
* [ ] When getting S3 Posix File Attributes in `S3Utils`, if the path is a directory, obtain the bucket ACL, then obtain its ACL grant permissions, convert them to Posix file permissions and return them with the response.

# Useful Links

* [Upplication/Amazon-S3-FileSystem-NIO2#94](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/issues/94) : Unable to change directories when exposed via Mina SFTP

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov

**Comment by ptirador** [comment]
HI @thomascollett,

I came across your [issue](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/issues/94) and [Pull Request](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/pull/96), as in the past you have contributed to the [Upplication/Amazon-S3-FileSystem-NIO2](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2) project. Would it be fine for you if we applied the changes of your Pull Request to our project?

Thanks in advance.
cc @carlspring

**Comment by thomascollett** [comment]
@ptirador @carlspring please go ahead

**Comment by carlspring** [comment]
Thanks for confirming, @thomascollett !
