### ISSUE TITLE
Where does amazon-test.properties go?

### ISSUE THREAD

**Issue by amarcionek** [carlspring/s3fs-nio#149]
Hi,

I'm trying to run the integration tests before submitting a PR. But I'm having a hard time getting the amazon-test.properties file to load. `EnvironmentBuilder.class.getResourceAsStream("/amazon-test.properties");` returns null. (I'd argue that should be checked for null before passing props.load because it took me more time than I'd like to admit to find the cause.)

On one hand, the path is /amazon-test.properties which would imply to me it has to be put in the root of whatever filesystem the source is on. If that is intended that could be problematic for people running on Windows.

However, even if I just change it to EnvironmentBuilder.class.getResourceAsStream("amazon-test.properties"); and put that file in either the root of the repo or in the target directory it still doesn't work.

Any advice?

Thanks,
Adam

**Comment by amarcionek** [comment]
FWIW, I managed to get it work by putting the file in the root of the C: But is that the expectation?

**Comment by carlspring** [comment]
Hi @amarcionek ,

This is meant to be in your `src/test/resources`.
