### ISSUE TITLE
Test cleanups

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#201]
# Task Description

We need to go over all the tests and remove all the test methods that are there just for the sake of code coverage to pass. Here is an example:
```java
    /**
     * http://stackoverflow.com/questions/9700179/junit-testing-helper-class-with-only-static-methods
     */
    @Test
    public void just_to_silence_coverage()
    {
        new AttributesUtils()
        {
            // ignore this
        };
    }
```

We should go over the rest of the classes and simply remove such tests, as they are of no value and are increasing the code coverage just for the sake of appearances, which is extremely bad. 

As part of this cleanup, all test case methods that are using underscores shoulc be converted to camelCase (check the example above, but there may be others).

# Tasks

The following tasks will need to be carried out:
* [ ] Drop any test methods that are simply there for the sake of skewing up the code coverage numbers.
* [ ] Go over the tests and make sure that all the methods in them are camelCase and make any changes that may be required.

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov

**Comment by nmonokov** [comment]
I'd like to work on this one

**Comment by carlspring** [comment]
Great! Feel free to dig in! :)

**Comment by nmonokov** [comment]
I have concerns about tests here. I see some of them just testing java.nio package. Isn't it a responsibility of the java dev team? To be precise, I'm talking about GetPathTest. Should i delete it?

**Comment by carlspring** [comment]
Not sure what you mean exactly, perhaps you could provide some more details?

**Comment by nmonokov** [comment]
The entire GetPathTest class consists of such tests as:
`    @Test
    void getPathWithEmptyEndpoint()
            throws IOException
    {
        FileSystem fs = FileSystems.newFileSystem(URI.create("s3:///"), ImmutableMap.<String, Object>of());
        Path path = fs.provider().getPath(URI.create("s3:///bucket/path/to/file"));

        assertEquals(path, fs.getPath("/bucket/path/to/file"));
        assertSame(path.getFileSystem(), fs);
    }`
This is unit test is testing the java.nio classes. There is no org.carlspring.cloud.storage.s3fs classes involved.

**Comment by nmonokov** [comment]
@carlspring Also this entire test class id kinda strange. Maybe I don't understand what `@S3IntegrationTest` means, but it seams like this test should be deleted as well.
```
/**
 * Class level {@link MinioIntegrationTest} annotation and class level {@link S3IntegrationTest} annotation.
 */
@MinioIntegrationTest
@S3IntegrationTest
public class CombinedIT extends BaseIntegrationTest
{

    private static final Logger logger = LoggerFactory.getLogger(S3MethodAnnotationIT.class);

    @Test
    public void testS3MethodShouldExecuteBecauseOfClassLevelAnnotation()
    {
        logger.debug(new Exception().getStackTrace()[0].getMethodName());
        assertTrue(true);
    }

    @Test
    public void testMinioMethodShouldExecuteBecauseOfClassLevelAnnotation()
    {
        logger.debug(new Exception().getStackTrace()[0].getMethodName());
        assertTrue(true);
    }

}
```

**Comment by carlspring** [comment]
> The entire GetPathTest class consists of such tests as:
> 
> ```
>     @Test
>     void getPathWithEmptyEndpoint()
>             throws IOException
>     {
>         FileSystem fs = FileSystems.newFileSystem(URI.create("s3:///"), ImmutableMap.<String, Object>of());
>         Path path = fs.provider().getPath(URI.create("s3:///bucket/path/to/file"));
> 
>         assertEquals(path, fs.getPath("/bucket/path/to/file"));
>         assertSame(path.getFileSystem(), fs);
>     }
> ```
> 
> This is unit test is testing the java.nio classes. There is no org.carlspring.cloud.storage.s3fs classes involved.

This is misleading. You need to have a closer look at the `setup` method:
```java
        fileSystem = s3fsProvider.newFileSystem(S3EndpointConstant.S3_GLOBAL_URI_TEST, null);
```

**Comment by nmonokov** [comment]
It's in example package, so I really don't know what is the purpose of such approach.

**Comment by carlspring** [comment]
> @carlspring Also this entire test class id kinda strange. Maybe I don't understand what `@S3IntegrationTest` means, but it seams like this test should be deleted as well.
> 
> ```
> /**
>  * Class level {@link MinioIntegrationTest} annotation and class level {@link S3IntegrationTest} annotation.
>  */
> @MinioIntegrationTest
> @S3IntegrationTest
> public class CombinedIT extends BaseIntegrationTest
> {
> 
>     private static final Logger logger = LoggerFactory.getLogger(S3MethodAnnotationIT.class);
> 
>     @Test
>     public void testS3MethodShouldExecuteBecauseOfClassLevelAnnotation()
>     {
>         logger.debug(new Exception().getStackTrace()[0].getMethodName());
>         assertTrue(true);
>     }
> 
>     @Test
>     public void testMinioMethodShouldExecuteBecauseOfClassLevelAnnotation()
>     {
>         logger.debug(new Exception().getStackTrace()[0].getMethodName());
>         assertTrue(true);
>     }
> 
> }
> ```

Don't touch this class. It's part of a re-work that is in progress. It will be used as a base class, but those tests are have not yet been re-worked, as this will be done in stages.

cc: @steve-todorov

**Comment by nmonokov** [comment]
@carlspring As for GetPathTest. Even with commented `@BeforeEach` and `extends S3UnitTestBase` the test is green. I you sure that this test is viable?

**Comment by nmonokov** [comment]
It's regarding `getPath` and `getAnotherPath` tests only

**Comment by nmonokov** [comment]
The only reason why part of tests in `GetPathTest` is failing is that in `S3UnitTestBase` base class there is a method which closes all fileSystem, thus the context is not refreshed and tests are failing. But if you run each test individually without `@BeforeEach` and `extends S3UnitTestBase` you'll have them all green. Which means, this entire unit test class is not testing the application, but is testing java.nio package. And this is unreasonable. But if you say it should stay here, I won't delete it.

**Comment by nmonokov** [comment]
Since this test was never fixed from 2013 maybe we should get rid of it? I'm not sure if this fixable.
![image](https://user-images.githubusercontent.com/10772631/106755951-c6d8c580-663f-11eb-8af6-2e7951ba0764.png)

**Comment by nmonokov** [comment]
As I see it was created this way, with "FIXME" comment.

**Comment by steve-todorov** [comment]
@nmonokov just FYI, we have inherited this code and some of the code might be "in-between" states which is why it might look misleading. When you are checking the tests you should be checking the git history as well which will point you to a ticket number - all of the new commits usually have `issue-XYZ: Some title` and maybe additional data. This will help you with differentiating what's new from what's old. 

`CombinedIT` and the tests in the `junit` package - yes, it "looks" like they do nothing, and that is intentional. I've created those specifically with that purpose for task #184. It is much easier to debug if the different kinds of tests are activated properly. It also serves as an "example" for the possible `annotation` combinations. This is important, because `MinIO` has an `S3` compatible API which allows you to run the same test for `S3` and `MinIO` and only add additional test cases which focus on "edge cases", rather than "copy/pasting" the same test around with only slightly different name. :)

**Comment by nmonokov** [comment]
@steve-todorov ok, got it. And what would you say about `GetPathTest` test class? It seems like it's testing nothing from the project. At first, it looks like it has to do something with file system from our provider. But actually it just stays there for no reason. You can just comment out all that code and units still pass.

**Comment by carlspring** [comment]
@ptirador , @mslowiak : Would you like to join in and share your thoughts? :)

**Comment by mslowiak** [comment]
@nmonokov
Would be great if you debug into the `FileSystems::newFileSystem(URI uri, Map<String,?> env, ClassLoader loader)` method.
The `S3FileSystemProvider::getScheme()` can be a hint for you.

**Comment by steve-todorov** [comment]
> I have concerns about tests here. I see some of them just testing java.nio package. Isn't it a responsibility of the java dev team? To be precise, I'm talking about GetPathTest. Should i delete it?

It looks like you might have misunderstood how the NIO filesystem works.
You have correctly spotted the usage of the `java.nio` package, but it's actually the entry point for testing our S3 implementation of the `java.nio` package.

Checkout the `S3UnitTestBase#getS3fsProvider` (I know, the name is misleading - we'll fix that at a later stage) and the `@BeforeEach` methods which are registering the `S3FileSystemProvider` as a file system provider. So when you call:

![image](https://user-images.githubusercontent.com/2303663/106790045-b0d8fe00-665b-11eb-96ba-3ad8fa439cad.png)

This would actually delegate to the `S3FileSystemProvider.newFileSystem` method

![image](https://user-images.githubusercontent.com/2303663/106790135-cd753600-665b-11eb-9292-48fbade1a49a.png)
