### ISSUE TITLE
Normalize '.' and '..' in paths

### ISSUE THREAD

**Issue by ennoruijters** [carlspring/s3fs-nio#382]
# Task Description
S3Path.normalize() currently just returns the path unmodified. This is inconvenient for users wanting to use S3FS as a replacement for more unix-like filesystem, where elements '.' and '..' have special meanings ('this directory', and 'parent directory').

We can make S3FS behave more unix-like by having normalize() effectively remove "./" and "\<dir\>/../".

# Notes

* S3 itself does not attach special meaning to these filenames, so it is perfectly legal to create an object with key "/abc/../file" distinct from "/file". If we add normalization, we would make such objects inaccessible. If this is particularly unwanted, we could make the behaviour configurable.
* `Paths.get().normalize()` on Windows also treats the `..` the same way.

# Tasks

The following tasks will need to be carried out:
* [x] Implement S3Path.normalize() that normalizes paths as if they were Unix paths.
* [x] Include unit tests.

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov

**Comment by carlspring** [comment]
@ennoruijters : Thank you very much for your contribution and apologies for the amount of time it took to get to it!
