### ISSUE TITLE
Can our project map the s3 bucket to the local file system?

### ISSUE THREAD

**Issue by youzi1030** [carlspring/s3fs-nio#423]
Can this project map the s3 bucket to the local file system?
Then use it for other operations like a file system.

**Comment by steve-todorov** [comment]
Hey @youzi1030, 

Apologies for the super late reply.

I am not entirely sure what you're asking. This project allows you to "mount" an s3 bucket and operate the same way you'd normally operate over a local file system. You can check out the documentation where you can find examples as well.

https://s3fs-nio.carlspring.org/reference/examples/basic-example/
