### ISSUE TITLE
Add a section in the documentation on how to set things up in AWS

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#56]
# Task Description

We should add a section in the wiki the explains:
* How to set up a bucket.
* How to set up a secret key and an access key.
* How to set up your region.
* How to use the `amazon-test.properties`.

Optimally, there should be some screenshots.

# Task Relationships

This task:
* Depends on: #22 

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio2-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
  * @sbespalov

**Comment by steve-todorov** [comment]
Added as part of PR #70
