### ISSUE TITLE
Rename all test methods that don't conform with the camel case convention

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#57]
# Task Description

Some test methods aren't following the camel case naming convention. We should rename these in order to be more consistent.

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio2-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
  * @sbespalov

**Comment by sonukushwaha403** [comment]
is the issue open to work on with???

**Comment by carlspring** [comment]
Hello, @sonukushwaha403 ,

Yes, it is! Feel free to pick it up.

**Comment by sonukushwaha403** [comment]
please assign it to me

**Comment by sonukushwaha403** [comment]
i am beginner ,and i am facing problem in setting up (running locally ), as I have cloned in mine local system, could you please help me out on running it locally .

**Comment by carlspring** [comment]
@sonukushwaha403 ,

You should be able to build the code and run the tests using Maven, if you would like to contribute a fix for this issue.

**Comment by sonukushwaha403** [comment]
will it run on intellije idea or i need to install other app, can you please suggest if so.

**Comment by carlspring** [comment]
Yes, it will. You need Maven 3.6.3, JDK8 or 11.

**Comment by ptirador** [comment]
Hi @carlspring! Can I work on this?

**Comment by carlspring** [comment]
Sure! Please, go ahead! :)
