### ISSUE TITLE
Add support for JDK 17 LTS

### ISSUE THREAD

**Issue by steve-todorov** [carlspring/s3fs-nio#689]
# Task Description

We need to add support for JDK 17 builds.

# Tasks

The following tasks will need to be carried out:
* [ ] Fix compilation issues (dependency updates might be needed)
* [ ] Add JDK 17 to the workflow matrix.

# Task Relationships

This task:
* Is a sub-task of: #
* Depends on: #
* Is a follow-up of: #
* Relates to: #

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov

**Comment by guicamest** [comment]
Hi, I think I can contribute to this task. I wanted to clarify the scope.

Is the intention to add '17' to the matrix in [build](https://github.com/guicamest/s3fs-nio/blob/master/.github/workflows/build.yml) or it also about using jdk 17 to [deploy](https://github.com/guicamest/s3fs-nio/blob/master/.github/workflows/deploy-tag.yaml) [deploy-snapshot](https://github.com/guicamest/s3fs-nio/blob/master/.github/workflows/command-deploy-pr-snapshot.yaml)?

So far, I only noticed one test (`InstallProviderTest.useZipProviderPathNotExists`) failing due to different exceptions being thrown :
```
expected: <java.nio.file.FileSystemNotFoundException> (jdk 8, 11)
but was: <java.nio.file.NoSuchFileException> (jdk 17)
```

**Comment by steve-todorov** [comment]
Hey @guicamest ,

Thanks for your interest in this task. 

The intention is to add JDK 17 to the matrix build so we know things are building as expected. 

However I don't think this task is a good fit for you to work on, because GH Actions has limitations in regards to changes made by external contributors. The GH actions will use the `master` revision of the GH Actions yaml files which means we wouldn't be able to actually test your changes in the CI.

I'll see if I could cherry-pick some of your changes and open a branch to test them out during the weekend.

**Comment by guicamest** [comment]
Thanks @steve-todorov ! I understand the limitation, thanks for taking over 🙏 

I have noticed a couple of tests failed, namely `fileIsReadableBucket` and `bucketIsDirectory` from `FilesIT`. Considering that they also fail in an _unrelated_ [PR](https://github.com/carlspring/s3fs-nio/actions/runs/5932049377/job/16085131095?pr=752) (it updates a dependency), I suspect they are flaky :(

**Comment by guicamest** [comment]
My two cents about the tests, it _looks_ latency related:

_[Successful Run](https://github.com/carlspring/s3fs-nio/actions/runs/6312107182/job/17137453978)_ ✔️ 
```
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ shouldReplaceExistingFileExample1() (4.2s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ shouldReplaceExistingFileExample2() (5s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ existsFile()
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ fileIsReadableBucket()
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ directoryStreamBaseBucketFindDirectoryTest() (1.2s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ existsFileWithSpace() (1.4s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ readAttributesString() (1.2s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ deleteFullDirTest() (15.1s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ bucketIsDirectory()
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ createTempDir() (1.7s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ readAttributesDirectory() (5.3s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ virtualDirectoryStreamWithVirtualSubFolderTest()
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ copyDir() (5.9s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ readAttributesFile() (1.1s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ moveFromDifferentProviders() (2.1s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ createTempFileAndWrite() (2.4s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ deleteFile() (2.1s)
```

_[Unsuccessful Run](https://github.com/carlspring/s3fs-nio/actions/runs/6337156687/job/17211648248)_ ❌ 
```
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ shouldReplaceExistingFileExample1() (5.4s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ shouldReplaceExistingFileExample2() (6.7s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ existsFile() (1.1s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✘ fileIsReadableBucket()
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ directoryStreamBaseBucketFindDirectoryTest() (1.6s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ existsFileWithSpace() (1.8s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ readAttributesString() (1.5s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ deleteFullDirTest() (19.7s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✘ bucketIsDirectory()
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ createTempDir() (2.3s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ readAttributesDirectory() (6.8s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ virtualDirectoryStreamWithVirtualSubFolderTest()
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ copyDir() (7.8s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ readAttributesFile() (1.4s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ moveFromDifferentProviders() (2.8s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ createTempFileAndWrite() (3.2s)
  org.carlspring.cloud.storage.s3fs.FilesIT ✔ deleteFile() (2.8s)
```

**Comment by steve-todorov** [comment]
You can safely ignore those two tests. They sometimes fail due to job concurrency issues  (not JVM concurrency, but rather matrix job concurrency).

**Comment by guicamest** [comment]
Makes total sense! 😅 

I don't know how the current s3 is setup, but do you think it'd be possible to update [build.yml](https://github.com/carlspring/s3fs-nio/blob/master/.github/workflows/build.yml#L128) with something like (_don't know if it'd be the correct github syntax_) 
> S3FS_BUCKET_NAME: ${{ github.event.pull_request.head.ref }} ${{ env.PR_NUMBER }} ${{ matrix.os }} ${{ matrix.java }}

so that builds from different PRs and different architectures do not interfere with each other? I could raise a PR for it if so.

**Comment by steve-todorov** [comment]
It's definitely possible, however it would be impractical.

Pretty much all of the tests already are using randomized paths via the [BaseTest#getTestBasePath](https://github.com/carlspring/s3fs-nio/blob/master/src/test/java/org/carlspring/cloud/storage/s3fs/BaseTest.java#L32). It generates a path with the package and class name and then uses UUID to generate a random path name.

Unfortunately there are some tests that are supposed to run against the **bucket itself** (i.e. the root path). In those cases you can't do anything other than generate per-matrix bucket. Although that is also possible, it then creates other headaches such as somebody having to delete them after builds. :)
