### ISSUE TITLE
master does not build?

### ISSUE THREAD

**Issue by stefanofornari** [carlspring/s3fs-nio#696]
# Task Description

Hello,

I have just downloaded master but it does not compile. Please see below the output.

```
./gradlew build

> Task :test
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
<=======------> 55% EXECUTING [1m 17s]
> :test > 109 tests completed, 109 failed
> :test > Executing test org.carlspring.cloud.storage.s3fs.S3UtilsTest
^C[ste s3fs-nio] o(= ./gradlew clean build

> Task :test
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

389 tests completed, 329 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/ste/Projects/s3fs-nio/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5m 5s
10 actionable tasks: 7 executed, 3 from cache
```

# Tasks

The following tasks will need to be carried out:
* [ ] Investigate the issue.
* [ ] Provide a fix.
* [ ] Test.

# Task Relationships

This task:
* Is a sub-task of:
* Depends on:
* Is a follow-up of:
* Relates to:
  * #693 

# Useful Links

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov

**Comment by steve-todorov** [comment]
Hey,

Could you please give more information about your setup? 
It's building just fine in the master as you can see in [gh actions](https://github.com/carlspring/s3fs-nio/actions/runs/5024263135/jobs/9009798761) (check the `Build and Test` step, other failures should be ignored as they will covered in #691). 

Since it's showing a lot of test failures I suspect you haven't configured the `amazon-test.properties` as mentioned in the docs:

* https://s3fs-nio.carlspring.org/contributing/developer-guide/#preparing-credentials
* [Sample](https://github.com/carlspring/s3fs-nio/blob/master/src/test/resources/amazon-test-sample.properties)

**Comment by carlspring** [comment]
Ciao Stefano,

Thanks for reporting this. We actually have an issue template for a reason.

What version of the JDK is this and what OS? You need to have the `amazon.properties` files in place.

We just merged the #693 pull request last night and you can see that it builds fine [here](https://github.com/carlspring/s3fs-nio/actions/runs/5032602246).

Could you please provide some more details?

**Comment by stefanofornari** [comment]
Hello,
thanks for your quick response. I have definitely not configured the
environment as I was a step before trying to contributing :)
I am going to set it up and let you know (and possibly close the issue).

PS: thanks Marting as well!
Ste

**Comment by stefanofornari** [comment]
does it require a real bucket and real access to AWS?

**Comment by carlspring** [comment]
Yes, it does.

**Comment by stefanofornari** [comment]
mhhh... can I also use a S3-Like service setting the entrypoint?
Ste

**Comment by stefanofornari** [comment]
Sorry to bother you guys, but I used the pom and maven all worked like a
charm... is that normal?
Ste

**Comment by carlspring** [comment]
You can try and tell us how it goes and which S3-like service this is. We were experimenting with Minio (#103).

**Comment by carlspring** [comment]
The `pom.xml` was up-to-date until recently. Since yesterday we have switched out efforts to Gradle.

@steve-todorov : The Maven build scripts should be removed as well.

**Comment by carlspring** [comment]
@stefanofornari : The more questions and feedback, the better. We are busy rebooting this project, which was in hibernation for a while. If you'd like to help out, let us know! :)

**Comment by steve-todorov** [comment]
@carlspring FYI, the `pom.xml` was removed as part of #692 :) 

> mhhh... can I also use a S3-Like service setting the entrypoint?

If you mean using `ARN`s or `S3 Access Points` the answer is no. It is not supported yet (check #131)

**Comment by stefanofornari** [comment]
Yep, I'll be happy to help, but I really have issues with gradle ( :( ). I
know, it's my problem, but I never get a gradle project to work at the
first shot.
I recovered the pom from before it was removed. But it is strange all tests
pass without setting any properties. Maybe it does not run all tests?
Let me know also if you want me to keep going commenting on this issue or
if you prefer any other channel.
FYI I am trying the StorJ S3 gateway.

Ste

**Comment by steve-todorov** [comment]
Without details about your setup it is hard to guess what might be wrong. 
Please fill out the following:

1. `java -version` 
2. Gradle version
3. OS (flavor and version)
4. Are you using `./gradlew` or you're using a distribution version you installed?

You can join our community channel here and ask your questions if you'd like:
https://chat.carlspring.org/channel/s3fs-nio-community

**Comment by stefanofornari** [comment]
>
> java -version
> openjdk version "1.8.0_362"
> OpenJDK Runtime Environment (build
> 1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09)
> OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)
>


> uname -a
> Linux minidesktop 5.4.0-148-generic #165~18.04.1-Ubuntu SMP Thu Apr 20
> 01:14:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
>

./gradlew --version
>
> ------------------------------------------------------------
> Gradle 8.1.1
> ------------------------------------------------------------
>
> Build time:   2023-04-21 12:31:26 UTC
> Revision:     1cf537a851c635c364a4214885f8b9798051175b
>
> Kotlin:       1.8.10
> Groovy:       3.0.15
> Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
> JVM:          1.8.0_362 (Private Build 25.362-b09)
> OS:           Linux 5.4.0-148-generic amd64
>

I am using the gradle as checked out from the project

HTH

Ste

**Comment by steve-todorov** [comment]
Try adding:
```
bash-5.1$ cat > src/test/resources/amazon-test.properties
# the "/" is mandatory at the moment.
s3fs.bucket.name=/<BUCKET_NAME>
s3fs.access.key=API_KEY
s3fs.secret.key=API_SECRET
s3fs.region=BUCKET_REGION
s3fs.protocol=https
```

Then do `./gradlew clean build --stacktrace` 

This should work - after all it's passing in GH Actions.
It's also building in docker so it's likely the property file.

**Comment by stefanofornari** [comment]
Any way I can provide the end point too?
Ste

**Comment by stefanofornari** [comment]
Just to close on the topic. I've got it to work without running ITs, which is good enough for me at least now. Thanks for your support and to put effort in this project.

**Comment by carlspring** [comment]
Thanks for letting us know! :)
